const areas = [
    { id: 0, name: "Select City", district: "" },
    { id: 1, name: "Agoncillo", district: "Batangas 3rd" },
    { id: 2, name: "Alfonso", district: "Cavite 8th" },
    { id: 3, name: "Alitagtag", district: "Batangas 3rd" },
    { id: 4, name: "Amadeo", district: "Cavite 7th" },
    { id: 5, name: "Anao", district: "Tarlac 5th" },
    { id: 6, name: "Angat", district: "Bulacan 3rd" },
    { id: 7, name: "Angono ", district: "Rizal 1st" },
    { id: 8, name: "Antipolo", district: "Rizal" },
    { id: 9, name: "Apalit", district: "Pampanga 1st" },
    { id: 10, name: "Arayat", district: "Pampanga 1st" },
    { id: 11, name: "Bacolor", district: "Pampanga 3rd" },
    { id: 12, name: "Bacoor", district: "Cavite 2nd" },
    { id: 13, name: "Balagtas", district: "Bulacan 2nd" },
    { id: 14, name: "Balayan", district: "Batangas 1st" },
    { id: 15, name: "Balete", district: "Batangas 3rd" },
    { id: 16, name: "Baliwag", district: "Bulacan 2nd" },
    { id: 17, name: "Bamban", district: "Tarlac 2nd" },
    { id: 18, name: "Baras", district: "Rizal 4th" },
    { id: 19, name: "Batangas", district: "Batangas 5th" },
    { id: 20, name: "Bauan", district: "Batangas 2nd" },
    { id: 21, name: "Binangonan", district: "Rizal 1st" },
    { id: 22, name: "Bocaue", district: "Bulacan 2nd" },
    { id: 23, name: "Bulakan", district: "Bulacan 1st" },
    { id: 24, name: "Bustos", district: "Bulacan 2nd" },
    { id: 25, name: "Cainta", district: "Rizal" },
    { id: 26, name: "Calaca", district: "Batangas 1st" },
    { id: 27, name: "Calatagan", district: "Batangas 1st" },
    { id: 28, name: "Caloocan", district: "Northern Manila" },
    { id: 29, name: "Calumpit", district: "Bulacan 1st" },
    { id: 30, name: "Camiling", district: "Tarlac 1st" },
    { id: 31, name: "Candaba", district: "Pampanga 1st" },
    { id: 32, name: "Capas", district: "Tarlac 1st" },
    { id: 33, name: "Cardona", district: "Rizal 3rd" },
    { id: 34, name: "Carmona", district: "Cavite 5th" },
    { id: 35, name: "Cavite City", district: "Cavite 1st" },
    { id: 36, name: "Concepcion", district: "Tarlac 1st" },
    { id: 37, name: "Cuenca", district: "Batangas 3rd" },
    { id: 38, name: "Dasmariñas", district: "Cavite 4th" },
    { id: 39, name: "Doña Remedios Trinidad", district: "Bulacan 3rd" },
    { id: 40, name: "Floridablanca", district: "Pampanga 1st" },
    { id: 41, name: "General Emilio Aguinaldo", district: "Cavite 8th" },
    { id: 42, name: "General Mariano Alvarez", district: "Cavite 5th" },
    { id: 43, name: "General Trias City", district: "Cavite 6th" },
    { id: 44, name: "Gerona", district: "Tarlac 1st" },
    { id: 45, name: "Guagua", district: "Pampanga 1st" },
    { id: 46, name: "Guiguinto", district: "Bulacan 2nd" },
    { id: 47, name: "Hagonoy", district: "Bulacan 1st" },
    { id: 48, name: "Ibaan", district: "Batangas 4th" },
    { id: 49, name: "Imus", district: "Cavite 3rd" },
    { id: 50, name: "Indang", district: "Cavite 7th" },
    { id: 51, name: "Jalajala", district: "Rizal 4th" },
    { id: 52, name: "Kawit", district: "Cavite 1st" },
    { id: 53, name: "La Paz", district: "Tarlac 2nd" },
    { id: 54, name: "Las Piñas", district: "Southern Manila" },
    { id: 55, name: "Laurel", district: "Batangas 3rd" },
    { id: 56, name: "Lemery", district: "Batangas 1st" },
    { id: 57, name: "Lian", district: "Batangas 1st" },
    { id: 58, name: "Lipa", district: "Batangas 4th" },
    { id: 59, name: "Lobo", district: "Batangas 2nd" },
    { id: 60, name: "Lubao", district: "Pampanga 1st" },
    { id: 61, name: "Mabalacat", district: "Pampanga" },
    { id: 62, name: "Mabini", district: "Batangas 2nd" },
    { id: 63, name: "Macabebe", district: "Pampanga 1st" },
    { id: 64, name: "Magalang", district: "Pampanga 1st" },
    { id: 65, name: "Magallanes", district: "Cavite 8th" },
    { id: 66, name: "Makati", district: "Southern Manila" },
    { id: 67, name: "Malabon", district: "Northern Manila" },
    { id: 68, name: "Malolos", district: "Bulacan 1st" },
    { id: 69, name: "Malvar", district: "Batangas 3rd" },
    { id: 70, name: "Mandaluyong", district: "Eastern Manila" },
    { id: 71, name: "Manila", district: "Capital" },
    { id: 72, name: "Maragondon", district: "Cavite 8th" },
    { id: 73, name: "Marikina", district: "Eastern Manila" },
    { id: 74, name: "Marilao", district: "Bulacan 4th" },
    { id: 75, name: "Masantol", district: "Pampanga 2nd" },
    { id: 76, name: "Mataas na kahoy", district: "Batangas 3rd" },
    { id: 77, name: "Mayantoc", district: "Tarlac 3rd" },
    { id: 78, name: "Mendez", district: "Cavite 8th" },
    { id: 79, name: "Mexico", district: "Pampanga 1st" },
    { id: 80, name: "Meycauayan", district: "Bulacan 4th" },
    { id: 81, name: "Minalin", district: "Pampanga 4th" },
    { id: 82, name: "Moncada", district: "Tarlac 1st" },
    { id: 83, name: "Morong", district: "Rizal 2nd" },
    { id: 84, name: "Muntinlupa", district: "Southern Manila" },
    { id: 85, name: "Naic", district: "Cavite 8th" },
    { id: 86, name: "Nasugbu", district: "Batangas 1st" },
    { id: 87, name: "Navotas", district: "Northern Manila" },
    { id: 88, name: "Norzagaray", district: "Bulacan 3rd" },
    { id: 89, name: "Noveleta", district: "Cavite 1st" },
    { id: 90, name: "Obando", district: "Bulacan 4th" },
    { id: 91, name: "Padre Garcia", district: "Batangas 4th" },
    { id: 92, name: "Pandi", district: "Bulacan 2nd" },
    { id: 93, name: "Paniqui", district: "Tarlac 1st" },
    { id: 94, name: "Paombong", district: "Bulacan 1st" },
    { id: 95, name: "Parañaque", district: "Southern Manila" },
    { id: 96, name: "Pasay", district: "Southern Manila" },
    { id: 97, name: "Pasig", district: "Eastern Manila" },
    { id: 98, name: "Pateros", district: "Southern Manila" },
    { id: 99, name: "Pililla", district: "Rizal 1st" },
    { id: 100, name: "Plaridel", district: "Bulacan 2nd" },
    { id: 101, name: "Porac", district: "Pampanga 1st" },
    { id: 102, name: "Pulilan", district: "Bulacan 1st" },
    { id: 103, name: "Pura", district: "Tarlac 4th" },
    { id: 104, name: "Quezon City", district: "Eastern Manila" },
    { id: 105, name: "Ramos", district: "Tarlac 1st" },
    { id: 106, name: "Rodriguez", district: "Rizal 1st" },
    { id: 107, name: "Rosario", district: "Batangas 4th" },
    { id: 108, name: "Rosario", district: "Cavite 1st" },
    { id: 109, name: "San Clemente", district: "Tarlac 5th" },
    { id: 110, name: "San Fernando", district: "Pampanga" },
    { id: 111, name: "San Idelfonso", district: "Bulacan 3rd" },
    { id: 112, name: "San Jose (Batangas)", district: "Batangas 4th" },
    { id: 113, name: "San Jose (Tarlac)", district: "Tarlac 3rd" },
    { id: 114, name: "San Jose Del Monte", district: "Bulacan SJDMC" },
    { id: 115, name: "San Juan", district: "Batangas 4th" },
    { id: 116, name: "San Juan", district: "Eastern Manila" },
    { id: 117, name: "San Luis", district: "Batangas 2nd" },
    { id: 118, name: "San Luis", district: "Pampanga 3rd" },
    { id: 119, name: "San Manuel", district: "Tarlac 4th" },
    { id: 120, name: "San Mateo", district: "Rizal 1st" },
    { id: 121, name: "San Miguel", district: "Bulacan 3rd" },
    { id: 122, name: "San Nicolas", district: "Batangas 3rd" },
    { id: 123, name: "San Pascual", district: "Batangas 2nd" },
    { id: 124, name: "San Rafael", district: "Bulacan 3rd" },
    { id: 125, name: "San Simon", district: "Pampanga 3rd" },
    { id: 126, name: "Santa Ana", district: "Pampanga 3rd" },
    { id: 127, name: "Santa Ignacia", district: "Tarlac 2nd" },
    { id: 128, name: "Santa Maria", district: "Bulacan 4th" },
    { id: 129, name: "Santa Rita", district: "Pampanga 4th" },
    { id: 130, name: "Santa Teresita", district: "Batangas 3rd" },
    { id: 131, name: "Santo Tomas", district: "Pampanga 4th" },
    { id: 132, name: "Sasmuan", district: "Pampanga 4th" },
    { id: 133, name: "Silang", district: "Cavite 5th" },
    { id: 134, name: "Taal", district: "Batangas 1st" },
    { id: 135, name: "Tagaytay", district: "Cavite 8th" },
    { id: 136, name: "Taguig", district: "Southern Manila" },
    { id: 137, name: "Talisay", district: "Batangas 3rd" },
    { id: 138, name: "Tanauan", district: "Batangas 3rd" },
    { id: 139, name: "Tanay", district: "Rizal 1st" },
    { id: 140, name: "Tanza", district: "Cavite 7th" },
    { id: 141, name: "Tarlac", district: "Tarlac" },
    { id: 142, name: "Taysan", district: "Batangas 4th" },
    { id: 143, name: "Taytay", district: "Rizal 1st" },
    { id: 144, name: "Teresa", district: "Rizal 2nd" },
    { id: 145, name: "Ternate", district: "Cavite 8th" },
    { id: 146, name: "Tingloy", district: "Batangas 2nd" },
    { id: 147, name: "Trece Martires", district: "Cavite 7th" },
    { id: 148, name: "Tuy", district: "Batangas 1st" },
    { id: 149, name: "Valenzuela", district: "Northern Manila" },
    { id: 150, name: "Victoria", district: "Tarlac 2nd" }
]

export const getAreas = () => {
    return areas
}

export const getArea = (areaId) => {

    const area = areas.find( area => areaId == area.id)

    return area
}

export const getAreaByName = (name) => {

    const area = areas.find( area => name == area.name )

    return area
}